(function(g){var window=this;var vE,AE,BE,FE,GE,Gja,ME,NE,Hja,QE,RE,SE,Ija,VE,YE,Jja,Kja,Lja,Mja,Nja,gF,kF,mF,oF,qF,Pja,CF,zF,Rja,BF,Qja,IF,Tja,Uja,JF,KF,MF,NF,LF,OF,QF,RF,SF,TF,PF,UF,Vja,XF,YF,Xja,ZF,Wja,WF,$F,aG,bG,cG,eG,gG,fG,dG,hG,iG,jG,kG,mG,nG,oG,pG,qG,rG,uG,AG,Yja,Zja,$ja,aka,HG,JG,bka,cka,MG,RG,TG,UG,VG,SG,WG,XG,ZG,$G,YG,iH,dka,lH,aH,mH,oH,hH,gH,fH,qH,dH,sH,rH,tH,uH,wH,yH,eka,fka,CH,AH,pH,FH,BH,GH,EH,DH,IH,hka,JH,KH,LH,NH,PH,QH,OH,UH,TH,SH,RH,VH,XH,xH,MH,WH,ZH,YH,$H,vH,nH,cH,bI,cI,dI,ika,jka,kka,fI,lka,gI,hI,kI,iI,lI,
nI,mka,oI,nka,pI,oka,pka,qka,mI,jI,xE;g.pE=function(a,b){return a>b?1:a<b?-1:0};g.qE=function(a,b){a.sort(b||g.pE)};g.rE=function(){};g.sE=function(a){if(!g.ea(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};g.tE=function(a,b,c,d,e){for(var f=0,k=a.length,l;f<k;){var p=f+k>>1,w;c?w=b.call(e,a[p],p,a):w=b(d,a[p]);0<w?f=p+1:(k=p,l=!w)}return l?f:~f};g.uE=function(a,b,c){return g.tE(a,c||g.pE,!1,b)};
vE=function(a,b,c,d){if(b=a.g[b]){var e=a.b;if(b=g.io(b,function(a){return e[a+1]==c&&e[a+2]==d}))return a.xd(b)}return!1};g.wE=function(a,b,c){a.b.set(b,c);return a};g.yE=function(a,b,c,d,e,f){g.ea(c)||(c&&(xE[0]=c.toString()),c=xE);for(var k=0;k<c.length;k++){var l=g.ed(b,c[k],d||a.handleEvent,e||!1,f||a.A||a);if(!l)break;a.g[l.key]=l}return a};
g.zE=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(g.fa(a)||g.ga(a))(0,g.D)(a,b,c);else for(var d=g.bo(a),e=g.co(a),f=e.length,k=0;k<f;k++)b.call(c,e[k],d&&d[k],a)};AE=function(a){g.wE(a,"zx",g.jo());return a};BE=function(a,b,c){g.ea(c)||(c=[String(c)]);g.Kg(a.b,b,c)};g.CE=function(a){g.E.call(this);this.A=a;this.g={}};g.DE=function(a){return g.go(a.b)};g.EE=function(a,b,c,d){Array.prototype.splice.apply(a,g.Ka(arguments,1))};
FE=function(){var a=g.qo("yt-remote-connected-devices")||[];g.qE(a);return a};GE=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})};g.HE=function(a,b,c){if(g.ga(b))(b=g.To(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var e=b[d],f=g.To(c,d);f&&(c.style[f]=e)}};
g.IE=function(a){var b=g.jc(a),c=new g.ao(0,0),d;d=b?g.jc(b):window.document;var e;(e=!g.Hb||9<=+g.mm)||(e=g.lc(d),e=g.Zn(e.b));if(a==(e?d.documentElement:d.body))return c;a=g.yo(a);b=g.DE(g.lc(b));c.x=a.left+b.x;c.y=a.top+b.y;return c};g.JE=function(){return g.qo("yt-remote-session-screen-id")};g.LE=function(){if(KE)return KE;var a=g.qo("yt-remote-device-id");a||(a=GE(),g.xo("yt-remote-device-id",a,31536E3));for(var b=FE(),c=1,d=a;g.Ea(b,d);)c++,d=a+"#"+c;return KE=d};
Gja=function(a){if(g.Fo(a))return[];var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.N)(a,function(a,b){return 0==b?a:a.substring(c.length)})};ME=function(a){a=a||{};this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""};NE=function(a,b){this.g=a;this.b=b+"::"};g.OE=function(a,b,c){c=g.uE(a,b,c);0>c&&g.EE(a,-(c+1),0,b)};Hja=function(a,b){return a===b};
g.PE=function(a,b){if("on"+a in b)return a;var c=g.un+a;return"on"+c in b?c:null};QE=function(){g.xo("yt-remote-lounge-token-expiration",!0,86400)};RE=function(){return g.qo("yt-remote-local-screens")||[]};SE=function(a){g.xo("yt-remote-connected-devices",a,86400)};g.TE=function(){var a=FE(),b=g.LE();g.Ea(a,b);g.JE()&&g.OE(a,b);a=Gja(a);if(g.Fo(a))try{a="remote_sid",g.Vd.remove(""+a,"/","youtube.com")}catch(c){}else try{g.Wd("remote_sid",a.join(","),-1)}catch(c){}};
g.UE=function(a){if(!a)return"null";var b=a.token?".."+a.token.slice(-6):"-",c=a.uuid?".."+a.uuid.slice(-6):"-";return'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+b+",uuid:"+c+"}"};Ija=function(a){return new ME(a)};VE=function(a){return{name:a.name,screenId:a.id,loungeToken:a.token,dialId:a.uuid}};g.WE=function(a,b){return a||b?!a!=!b?!1:a.id==b.id:!0};g.XE=function(a,b){return!!b&&(a.id==b||a.uuid==b)};
YE=function(a){this.b=this.name=this.id="";this.status="UNKNOWN";a&&(this.id=a.id||"",this.name=a.name||"",this.b=a.activityId||"",this.status=a.status||"UNKNOWN")};g.ZE=function(a){var b=new g.Id;return b.isAvailable()?a?new NE(b,a):b:null};Jja=function(a,b){return g.Do(a,b)};g.$E=function(a,b,c){if(!g.fa(a)||!g.fa(b)||a.length!=b.length)return!1;var d=a.length;c=c||Hja;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return!1;return!0};
g.aF=function(a,b){g.td.call(this);this.b=a||1;this.g=b||g.ba;this.o=(0,g.x)(this.mJ,this);this.A=(0,g.G)()};g.bF=function(a,b){a.b=b;a.Nd&&a.enabled?(a.stop(),a.start()):a.Nd&&a.stop()};Kja=function(a,b,c,d){var e=new g.yg(null,void 0);a&&g.zg(e,a);b&&g.Ag(e,b);c&&g.Bg(e,c);d&&(e.o=d);return e};g.dF=function(){if(!cF){var a=g.ZE();a&&(cF=new g.Rd(a))}return cF?!!cF.get("yt-remote-use-staging-server"):!1};
g.eF=function(a){a||(g.up("yt-remote-session-screen-id"),g.up("yt-remote-session-video-id"));g.TE();a=FE();g.Ga(a,g.LE());SE(a)};Lja=function(a,b){g.xo("yt-remote-session-browser-channel",a);g.xo("yt-remote-session-screen-id",b);var c=FE(),d=g.LE();g.Ea(c,d)||c.push(d);SE(c);g.TE()};g.fF=function(){return g.qo("yt-remote-online-dial-devices")||[]};Mja=function(a){g.xo("yt-remote-online-screens",a,60)};
Nja=function(a){5<a.length&&(a=a.slice(a.length-5));var b=(0,g.N)(RE(),function(a){return a.loungeToken}),c=(0,g.N)(a,function(a){return a.loungeToken});(0,g.cm)(c,function(a){return!g.Ea(b,a)})&&QE();g.xo("yt-remote-local-screens",a,31536E3)};gF=function(){return g.qo("yt-remote-session-browser-channel")};g.hF=function(a,b){return g.io(a,function(a){return g.XE(a,b)})};g.iF=function(a,b){return g.io(a,function(a){return g.WE(a,b)})};g.jF=function(a){return(0,g.N)(a,function(a){return new YE(a)})};
kF=function(a){return g.ea(a)?"["+g.N(a,g.UE).join(",")+"]":"null"};g.lF=function(a){return g.ea(a)?(0,g.N)(a,Ija):[]};
mF=function(a){this.app=this.name=this.id="";this.type="REMOTE_CONTROL";this.Qq=this.username="";this.connected=!1;this.capabilities=new g.Ap;this.xa="u";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.Qq=a.userAvatarUri||"",this.xa=a.theme||"u",this.capabilities=new g.Ap((0,g.Ac)((a.capabilities||"").split(","),g.oa(Jja,Oja))))};
g.nF=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{g.xc(a);var c=g.jc(a);a.appendChild(c.createTextNode(String(b)))}};oF=function(){};g.pF=function(a){var b=g.da(a);if("object"==b||"array"==b){if(g.ia(a.clone))return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=g.pF(a[c]);return b}return a};
qF=function(a,b){var c=g.Ca(a,b,void 0);0<=c&&g.Fa(a,c)};g.rF=function(a,b){g.Ea(a,b)||a.push(b)};g.sF=function(){this.b=[];this.g=[]};g.tF=function(a){g.Fo(a.b)&&(a.b=a.g,a.b.reverse(),a.g=[])};g.uF=function(a,b){a.g.push(b)};g.vF=function(a){g.tF(a);return a.b.pop()};g.xF=function(a,b){a==wF.length?b(null):Pja(wF[a],function(c){c?b(wF[a]):g.xF(a+1,b)})};
Pja=function(a,b){var c=new window.XMLHttpRequest;c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};c.onerror=function(){b(!1)};try{c.open("GET","chrome-extension://"+a+g.yF,!0),c.send()}catch(d){b(!1)}};CF=function(a){zF();AF.push(a);BF(AF)};g.DF=function(a,b){zF();var c=AF,d=Qja(a,String(b));g.Fo(c)?Rja(d):(BF(c),(0,g.D)(c,function(a){a(d)}))};zF=function(){AF||(AF=g.r("yt.mdx.remote.debug.handlers_")||[],g.q("yt.mdx.remote.debug.handlers_",AF,void 0))};
Rja=function(a){var b=(EF+1)%50;EF=b;FF[b]=a;GF||(GF=49==b)};BF=function(a){var b=FF;if(b[0]){var c=EF,d=GF?c:-1;do{var d=(d+1)%50,e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);FF=Array(50);EF=-1;GF=!1}};Qja=function(a,b){var c=((0,g.G)()-Sja)/1E3;c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")};g.HF=function(a){g.Vw.call(this);this.D=a;this.b=[]};
IF=function(a,b){var c=a.get(b.uuid)||a.get(b.id);if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.b.push(b);return!0};Tja=function(a,b){var c=a.b.length!=b.length;a.b=(0,g.Ac)(a.b,function(a){return!!g.iF(b,a)});for(var d=0,e=b.length;d<e;d++)c=IF(a,b[d])||c;return c};Uja=function(a,b){var c=a.b.length;a.b=(0,g.Ac)(a.b,function(a){return!g.WE(a,b)});return a.b.length<c};JF=function(a,b){g.DF(a.D,b)};
KF=function(a,b,c,d){g.Vw.call(this);this.D=a;this.C=b;this.A=c;this.B=d;this.o=0;this.b=null;this.g=window.NaN};MF=function(a){g.HF.call(this,"LocalScreenService");this.o=a;this.g=window.NaN;LF(this);JF(this,"Initializing with "+kF(this.b))};NF=function(a){if(a.b.length){var b=(0,g.N)(a.b,function(a){return a.id}),c=a.o.lh("/pairing/get_lounge_token_batch");a.o.sendRequest("POST",c,{screen_ids:b.join(",")},(0,g.x)(a.EJ,a),(0,g.x)(a.DJ,a))}};
LF=function(a){var b=g.lF(RE()),b=(0,g.Ac)(b,function(a){return!a.uuid});return Tja(a,b)};OF=function(a,b){Nja((0,g.N)(a.b,VE));b&&QE()};QF=function(a,b){g.Vw.call(this);this.B=b;for(var c=g.qo("yt-remote-online-screen-ids")||"",c=c?c.split(","):[],d={},e=this.B(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ea(c,l)}this.b=d;this.C=a;this.o=this.A=window.NaN;this.g=null;PF("Initialized with "+g.Nd(this.b))};
RF=function(a,b,c){var d=a.C.lh("/pairing/get_screen_availability");a.C.sendRequest("POST",d,{lounge_token:b.token},(0,g.x)(function(a){a=a.screens||[];for(var d=0,k=a.length;d<k;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))};SF=function(a,b){var c;a:if(g.Eo(b)!=g.Eo(a.b))c=!1;else{c=g.Oa(b);for(var d=0,e=c.length;d<e;++d)if(!a.b[c[d]]){c=!1;break a}c=!0}c||(PF("Updated online screens: "+g.Nd(a.b)),a.b=b,a.publish("screenChange"));Vja(a)};
TF=function(a){(0,window.isNaN)(a.o)||g.Bd(a.o);a.o=(0,g.Ad)((0,g.x)(a.pu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)};PF=function(a){g.DF("OnlineScreenService",a)};UF=function(a){var b={};(0,g.D)(a.B(),function(a){a.token?b[a.token]=a.id:this.Ab("Requesting availability of screen w/o lounge token.")});return b};
Vja=function(a){var b=g.Oa(g.Ma(a.b,function(a){return a}));g.qE(b);b.length?g.xo("yt-remote-online-screen-ids",b.join(","),60):g.up("yt-remote-online-screen-ids");a=(0,g.Ac)(a.B(),function(a){return!!this.b[a.id]},a);Mja((0,g.N)(a,VE))};g.VF=function(a){g.HF.call(this,"ScreenService");this.C=a;this.g=this.o=null;this.A=[];this.B={};Wja(this)};
XF=function(a,b,c,d,e,f){JF(a,"getAutomaticScreenByIds "+c+" / "+b);c||(c=a.B[b]);var k=a.zd();if(k=(c?g.hF(k,c):null)||g.hF(k,b)){k.uuid=b;var l=WF(a,k);RF(a.g,l,function(a){e(a?l:null)})}else c?Xja(a,c,(0,g.x)(function(a){var f=WF(this,new ME({name:d,screenId:c,loungeToken:a,dialId:b||""}));RF(this.g,f,function(a){e(a?f:null)})},a),f):e(null)};YF=function(a,b){for(var c=0,d=a.b.length;c<d;++c)if(a.b[c].name==b)return a.b[c];return null};
Xja=function(a,b,c,d){JF(a,"requestLoungeToken_ for "+b);var e={Sd:{screen_ids:b},method:"POST",context:a,rb:function(a,e){var l=e&&e.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},onError:function(){d(Error("Request screen lounge token failed"))}};g.ye(a.C.lh("/pairing/get_lounge_token_batch"),e)};ZF=function(a){a.b=a.o.zd();for(var b=g.Kq(a.B),c=0,d=a.b.length;c<d;++c){var e=a.b[c];e.uuid=b[e.id]||""}JF(a,"Updated manual screens: "+kF(a.b))};
Wja=function(a){$F(a);a.o=new MF(a.C);a.o.subscribe("screenChange",(0,g.x)(a.IJ,a));ZF(a);a.A=g.lF(g.qo("yt-remote-automatic-screen-cache")||[]);$F(a);JF(a,"Initializing automatic screens: "+kF(a.A));a.g=new QF(a.C,(0,g.x)(a.zd,a,!0));a.g.subscribe("screenChange",(0,g.x)(function(){this.publish("onlineScreenChange")},a))};
WF=function(a,b){var c=a.get(b.id);c?(c.uuid=b.uuid,b=c):((c=g.hF(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.xo("yt-remote-automatic-screen-cache",(0,g.N)(a.A,VE)));$F(a);a.B[b.uuid]=b.id;g.xo("yt-remote-device-id-map",a.B,31536E3);return b};$F=function(a){a.B=g.qo("yt-remote-device-id-map")||{}};aG=function(a,b,c){g.Vw.call(this);this.L=c;this.G=a;this.g=b;this.o=null};bG=function(a,b){g.DF(a.L,b)};cG=function(a,b){g.DF(a.L,b)};
eG=function(a,b){aG.call(this,a,b,"CastSession");this.b=null;this.B=0;this.A=null;this.D=(0,g.x)(this.yS,this);this.C=(0,g.x)(this.QP,this);this.B=(0,g.Ad)((0,g.x)(function(){dG(this,null)},this),12E4)};gG=function(a){var b=a.A.videoId||a.A.videoIds[a.A.index];b&&fG(a,"flingVideo",{videoId:b,currentTime:a.A.currentTime||0});a.A=null};
fG=function(a,b,c){bG(a,"sendYoutubeMessage_: "+b+" "+g.Nd(c));var d={};d.type=b;c&&(d.data=c);a.b?a.b.sendMessage("urn:x-cast:com.google.youtube.mdx",d,g.u,(0,g.x)(function(){cG(this,"Failed to send message: "+b+".")},a)):cG(a,"Sending yt message without session: "+g.Nd(d))};dG=function(a,b){g.Bd(a.B);if(b){if(bG(a,"onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.x)(a.Ro,a),d=(0,g.x)(a.od,a);a.oy(b,c,d,5)}}else a.od(Error("Waiting for session status timed out."))};
hG=function(a,b){aG.call(this,a,b,"DialSession");this.B=this.F=null;this.H="";this.A=null;this.D=g.u;this.C=window.NaN;this.K=(0,g.x)(this.BS,this);this.b=g.u};iG=function(a){a.b=a.G.mD(a.H,a.g.label,a.g.friendlyName,(0,g.x)(function(a){this.b=g.u;this.Ro(a)},a),(0,g.x)(function(a){this.b=g.u;this.od(a)},a))};jG=function(a){var b={};b.pairingCode=a.H;if(a.A){var c=a.A.index||0,d=a.A.currentTime||0;b.v=a.A.videoId||a.A.videoIds[c];b.t=d}g.dF()&&(b.env_useStageMdx=1);return g.$b(b)};
kG=function(a,b){aG.call(this,a,b,"ManualSession");this.b=(0,g.Ad)((0,g.x)(this.Zi,this,null),150)};g.lG=function(a){g.Vw.call(this);this.g=a;this.b=null;this.B=!1;this.o=[];this.A=(0,g.x)(this.JO,this)};mG=function(a,b){return b?g.io(a.o,function(a){return g.XE(b,a.label)},a):null};nG=function(a){g.DF("Controller",a)};oG=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)};pG=function(a){return a.B||!!a.o.length||!!a.b};
qG=function(a,b,c){g.Sc(a.b);(a.b=b)?(c?a.publish("yt-remote-cast2-receiver-resumed",b.g):a.publish("yt-remote-cast2-receiver-selected",b.g),b.subscribe("sessionScreen",(0,g.x)(a.fB,a,b)),b.o?a.publish("yt-remote-cast2-session-change",b.o):c&&a.b.Zi(null)):a.publish("yt-remote-cast2-session-change",null)};
rG=function(a){var b=a.g.lD(),c=a.b&&a.b.g;a=(0,g.N)(b,function(a){c&&g.XE(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,f=mG(this,a);f?(f.label=b,f.friendlyName=a.name):(f=new window.chrome.cast.Receiver(b,a.name),f.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return f},a);c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a};
g.sG=function(a){this.g=null;this.index=-1;this.videoId=this.o="";this.volume=this.b=-1;this.muted=!1;this.D=null;this.C=this.B=0;this.A=null;this.reset(a)};g.tG=function(a,b){if(a.o)throw Error(b+" is not allowed in V3.");};uG=function(a){a.D=null;a.A=null;a.b=-1;a.B=0;a.C=(0,g.G)()};g.vG=function(a){a.index=-1;a.videoId="";uG(a)};g.wG=function(a){return a.o?a.videoId:a.g[a.index]};g.xG=function(a,b){a.B=b;a.C=(0,g.G)()};g.yG=function(a){switch(a.b){case 1:return((0,g.G)()-a.C)/1E3+a.B;case -1E3:return 0}return a.B};
g.zG=function(a,b){g.tG(a,"setVideoId");var c=a.index;a.index=(0,g.Da)(a.g,b);c!=a.index&&uG(a)};AG=function(a,b,c){g.tG(a,"setPlaylist");c=c||g.wG(a);g.$E(a.g,b)&&c==g.wG(a)||(a.g=g.Ia(b),g.zG(a,c))};g.BG=function(a,b){g.tG(a,"add");return b&&!g.Ea(a.g,b)?(a.g.push(b),!0):!1};
g.CG=function(a){var b={};b.videoIds=g.Ia(a.g);b.index=a.index;b.listId=a.o;b.videoId=a.videoId;b.playerState=a.b;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.D;b.trackData=g.pF(a.A);b.playerTime=a.B;b.playerTimeAt=a.C;return b};Yja=function(a,b){this.action=a;this.ya=b||null};Zja=function(){if(!("cast"in window))return!1;var a=window.cast||{};return"ActivityStatus"in a&&"Api"in a&&"LaunchRequest"in a&&"Receiver"in a};g.DG=function(a){g.DF("CAST",a)};
$ja=function(a){var b=g.EG();b&&b.logMessage&&b.logMessage(a)};
g.IG=function(){if(!g.r("yt.mdx.remote.castv2_")&&!FG&&(g.Fo(GG)&&g.Ja(GG,g.fF()),Zja())){var a=g.EG();a?(a.removeReceiverListener("YouTube",HG),a.addReceiverListener("YouTube",HG),g.DG("API initialized in the other binary")):(a=new window.cast.Api,g.q("yt.mdx.remote.castapi.api_",a,void 0),a.addReceiverListener("YouTube",HG),a.setReloadTabRequestHandler&&a.setReloadTabRequestHandler(function(){(0,g.Ad)(function(){window.location.reload(!0)},1E3)}),CF($ja),g.DG("API initialized"));FG=!0}};
aka=function(a){var b=g.Ca(GG,function(b){return b.id==a.id});0<=b&&(GG[b]={id:a.id,name:a.name,activityId:a.b,status:a.status})};HG=function(a){a.length&&g.DG("Updating receivers: "+g.Nd(a));bka(a);g.Fk("yt-remote-cast-device-list-update");(0,g.D)(JG(),function(a){cka(a.id)});(0,g.D)(a,function(a){if(a.isTabProjected){var c=g.KG(a.id);g.DG("Detected device: "+c.id+" is tab projected. Firing DEVICE_TAB_PROJECTED event.");(0,g.Ad)(function(){g.Fk("yt-remote-cast-device-tab-projected",c.id)},1E3)}})};
g.LG=function(a,b){g.DG("Updating "+a+" activity status: "+g.Nd(b));var c=g.KG(a);c?(b.activityId&&(c.b=b.activityId),c.status="running"==b.status?"RUNNING":"stopped"==b.status?"STOPPED":"error"==b.status?"ERROR":"UNKNOWN","RUNNING"!=c.status&&(c.b=""),aka(c),g.Fk("yt-remote-cast-device-status-update",c)):g.DG("Device not found")};JG=function(){g.IG();return g.jF(GG)};
bka=function(a){a=(0,g.N)(a,function(a){var c={id:a.id,name:g.Bp(a.name)};if(a=g.KG(a.id))c.activityId=a.b,c.status=a.status;return c});g.sE(GG);g.Ja(GG,a)};g.KG=function(a){var b=JG();return g.io(b,function(b){return b.id==a})||null};cka=function(a){var b=g.KG(a),c=g.EG();c&&b&&b.b&&c.getActivityStatus(b.b,function(b){"error"==b.status&&(b.status="stopped");g.LG(a,b)})};g.EG=function(){return g.r("yt.mdx.remote.castapi.api_")};MG=function(a,b){this.b=b?g.Ld:g.Kd};
g.NG=function(a,b,c){g.E.call(this);this.A=null!=c?(0,g.x)(a,c):a;this.o=b;this.g=(0,g.x)(this.kP,this);this.b=[]};g.OG=function(a){a.mh=g.Rw(a.g,a.o);a.A.apply(null,a.b)};RG=function(){};TG=function(a){var b;(b=a.b)||(b={},SG(a)&&(b[0]=!0,b[1]=!0),b=a.b=b);return b};UG=function(){};VG=function(a){return(a=SG(a))?new window.ActiveXObject(a):new window.XMLHttpRequest};
SG=function(a){if(!a.g&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.g=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.g};
WG=function(a,b,c,d,e){this.b=a;this.o=c;this.F=d;this.D=e||1;this.B=45E3;this.A=new g.CE(this);this.g=new g.aF;g.bF(this.g,250)};XG=function(){return!g.Hb||10<=+g.mm};ZG=function(a,b,c){a.Di=1;a.Yf=AE(b.clone());a.Ch=c;a.C=!0;YG(a,null)};$G=function(a,b,c,d,e){a.Di=1;a.Yf=AE(b.clone());a.Ch=null;a.C=c;e&&(a.aC=!1);YG(a,d)};
YG=function(a,b){a.Jl=(0,g.G)();aH(a);a.qg=a.Yf.clone();BE(a.qg,"t",a.D);a.lm=0;a.Sb=a.b.sr(a.b.Ql()?b:null);0<a.hs&&(a.cp=new g.NG((0,g.x)(a.hD,a,a.Sb),a.hs));a.A.listen(a.Sb,"readystatechange",a.sQ);var c=a.nh?g.Lq(a.nh):{};a.Ch?(a.Tp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Sb.send(a.qg,a.Tp,a.Ch,c)):(a.Tp="GET",a.aC&&!g.Ib&&(c.Connection="close"),a.Sb.send(a.qg,a.Tp,null,c));a.b.je(1)};
iH=function(a,b,c){for(var d=!0;!a.Yg&&a.lm<c.length;){var e=dka(a,c);if(e==bH){4==b&&(a.oh=4,cH(),d=!1);dH(null);break}else if(e==eH){a.oh=4;cH();dH(c);d=!1;break}else dH(e),fH(a,e)}4==b&&0==c.length&&(a.oh=1,cH(),d=!1);a.re=a.re&&d;d||(dH(c),gH(a),hH(a))};dka=function(a,b){var c=a.lm,d=b.indexOf("\n",c);if(-1==d)return bH;c=+b.substring(c,d);if((0,window.isNaN)(c))return eH;d+=1;if(d+c>b.length)return bH;var e=b.substr(d,c);a.lm=d+c;return e};
lH=function(a,b){a.Jl=(0,g.G)();aH(a);var c=b?window.location.hostname:"";a.qg=a.Yf.clone();g.wE(a.qg,"DOMAIN",c);g.wE(a.qg,"t",a.D);try{a.te=new window.ActiveXObject("htmlfile")}catch(w){gH(a);a.oh=7;cH();hH(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e=e+"\\x3c";else if(">"==k)e=e+"\\x3e";else{if(k in jH)k=jH[k];else if(k in kH)k=jH[k]=kH[k];else{var l=k,p=k.charCodeAt(0);if(31<p&&127>p)l=k;else{if(256>p){if(l="\\x",16>p||256<p)l+="0"}else l=
"\\u",4096>p&&(l+="0");l+=p.toString(16).toUpperCase()}k=jH[k]=l}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.tb(g.$a("b/12014412"),d);a.te.open();a.te.write(g.qb(c));a.te.close();a.te.parentWindow.m=(0,g.x)(a.tP,a);a.te.parentWindow.d=(0,g.x)(a.oB,a,!0);a.te.parentWindow.rpcClose=(0,g.x)(a.oB,a,!1);c=a.te.createElement("DIV");a.te.parentWindow.document.body.appendChild(c);d=g.jb(a.qg.toString());d=g.ua(g.gb(d));d=g.tb(g.$a("b/12014412"),'<iframe src="'+d+'"></iframe>');
c.innerHTML=g.qb(d);a.b.je(1)};aH=function(a){a.Av=(0,g.G)()+a.B;mH(a,a.B)};mH=function(a,b){if(null!=a.Kj)throw Error("WatchDog timer not null");a.Kj=nH((0,g.x)(a.MP,a),b)};oH=function(a){a.Kj&&(g.ba.clearTimeout(a.Kj),a.Kj=null)};hH=function(a){a.b.sy()||a.Yg||a.b.Oo(a)};gH=function(a){oH(a);g.Sc(a.cp);a.cp=null;a.g.stop();a.A.removeAll();if(a.Sb){var b=a.Sb;a.Sb=null;pH(b);b.dispose()}a.te&&(a.te=null)};fH=function(a,b){try{a.b.aB(a,b),a.b.je(4)}catch(c){}};qH=function(){};
dH=function(a){if(a&&"y2f%"!=a)try{var b=g.Ld(a);if(b)for(a=0;a<b.length;a++)if(g.ea(b[a])){var c=b[a];if(!(2>c.length)){var d=c[1];if(g.ea(d)&&!(1>d.length)){var e=d[0];if("noop"!=e&&"stop"!=e)for(var f=1;f<d.length;f++)d[f]=""}}}g.Nd(b)}catch(k){}};sH=function(a,b,c,d,e){new qH;if(0==d)c(!1);else{var f=e||0;d--;rH(a,b,function(e){e?c(!0):g.ba.setTimeout(function(){sH(a,b,c,d,f)},f)})}};
rH=function(a,b,c){new qH;var d=new window.Image;d.onload=function(){try{tH(d),c(!0)}catch(a){}};d.onerror=function(){try{tH(d),c(!1)}catch(a){}};d.onabort=function(){try{tH(d),c(!1)}catch(a){}};d.ontimeout=function(){try{tH(d),c(!1)}catch(a){}};g.ba.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);d.src=a};tH=function(a){a.onload=null;a.onerror=null;a.onabort=null;a.ontimeout=null};uH=function(a){this.b=a;this.g=new MG(0,!0)};
wH=function(a){var b=vH(a.b,a.fk,"/mail/images/cleardot.gif");AE(b);sH(b.toString(),5E3,(0,g.x)(a.QH,a),3,2E3);a.je(1)};yH=function(a){var b=a.b.H;if(null!=b)cH(),b?(cH(),xH(a.b,a,!1)):(cH(),xH(a.b,a,!0));else if(a.rd=new WG(a,0,void 0,void 0,void 0),a.rd.nh=a.ds,b=a.b,b=vH(b,b.Ql()?a.Ak:null,a.gs),cH(),XG())BE(b,"TYPE","xmlhttp"),$G(a.rd,b,!1,a.Ak,!1);else{BE(b,"TYPE","html");var c=a.rd;a=!!a.Ak;c.Di=3;c.Yf=AE(b.clone());lH(c,a)}};
g.zH=function(a){g.td.call(this);this.headers=new g.Ab;this.L=a||null;this.o=!1;this.K=this.b=null;this.S=this.G="";this.g=0;this.C="";this.A=this.N=this.F=this.M=!1;this.B=0;this.D=null;this.X="";this.H=this.R=!1};eka=function(a){return g.Hb&&g.Mb(9)&&g.ha(a.timeout)&&g.n(a.ontimeout)};fka=function(a){return"content-type"==a.toLowerCase()};CH=function(a,b){a.o=!1;a.b&&(a.A=!0,a.b.abort(),a.A=!1);a.C=b;a.g=5;AH(a);BH(a)};AH=function(a){a.M||(a.M=!0,a.U("complete"),a.U("error"))};
pH=function(a,b){a.b&&a.o&&(DH(a,"Aborting"),a.o=!1,a.A=!0,a.b.abort(),a.A=!1,a.g=b||7,a.U("complete"),a.U("abort"),BH(a))};
FH=function(a){if(a.o&&"undefined"!=typeof g.Zl)if(a.K[1]&&4==EH(a)&&2==a.getStatus())DH(a,"Local request error detected and ignored");else if(a.F&&4==EH(a))g.Rw(a.ZA,0,a);else if(a.U("readystatechange"),4==EH(a)){DH(a,"Request complete");a.o=!1;try{var b=a.getStatus(),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Qb(1,String(a.G));if(!f&&g.ba.self&&g.ba.self.location)var k=g.ba.self.location.protocol,
f=k.substr(0,k.length-1);e=!gka.test(f?f.toLowerCase():"")}d=e}if(d)a.U("complete"),a.U("success");else{a.g=6;var l;try{l=2<EH(a)?a.b.statusText:""}catch(p){l=""}a.C=l+" ["+a.getStatus()+"]";AH(a)}}finally{BH(a)}}};BH=function(a,b){if(a.b){GH(a);var c=a.b,d=a.K[0]?g.u:null;a.b=null;a.K=null;b||a.U("ready");try{c.onreadystatechange=d}catch(e){}}};GH=function(a){a.b&&a.H&&(a.b.ontimeout=null);g.ha(a.D)&&(g.Sw(a.D),a.D=null)};EH=function(a){return a.b?a.b.readyState:0};
g.HH=function(a){try{return a.b?a.b.responseText:""}catch(b){return""}};DH=function(a,b){return b+" ["+a.S+" "+a.G+" "+a.getStatus()+"]"};IH=function(a,b,c){this.D=a||null;this.b=1;this.g=[];this.A=[];this.G=new qH;this.B=new MG(0,!0);this.F=b||null;this.H=null!=c?c:null};hka=function(a,b){this.b=a;this.map=b;this.context=null};JH=function(a){g.Tc.call(this,"statevent",a)};KH=function(a,b){g.Tc.call(this,"timingevent",a);this.size=b};LH=function(a){g.Tc.call(this,"serverreachability",a)};
NH=function(a){if(a.Lf){var b=a.Lf;b.rd&&(b.rd.cancel(),b.rd=null);b.ff=-1;a.Lf=null}a.Kb&&(a.Kb.cancel(),a.Kb=null);a.Ye&&(g.ba.clearTimeout(a.Ye),a.Ye=null);MH(a);a.Wc&&(a.Wc.cancel(),a.Wc=null);a.Rf&&(g.ba.clearTimeout(a.Rf),a.Rf=null)};PH=function(a,b){if(0==a.b)throw Error("Invalid operation: sending map when state is closed");1E3==a.g.length&&g.Nd(b);a.g.push(new hka(a.qM++,b));2!=a.b&&3!=a.b||OH(a)};QH=function(a){var b=0;a.Kb&&b++;a.Wc&&b++;return b};
OH=function(a){a.Wc||a.Rf||(a.Rf=nH((0,g.x)(a.jB,a),0),a.vk=0)};UH=function(a,b){if(1==a.b){if(!b){a.kl=Math.floor(1E5*Math.random());var c=a.kl++,d=new WG(a,0,"",c,void 0);d.nh=null;var e=RH(a),f=a.Jn.clone();g.wE(f,"RID",c);a.D&&g.wE(f,"CVER",a.D);SH(a,f);ZG(d,f,e);a.Wc=d;a.b=2}}else 3==a.b&&(b?TH(a,b):0!=a.g.length&&(a.Wc||TH(a)))};
TH=function(a,b){var c,d;b?6<a.Zg?(a.g=a.A.concat(a.g),a.A.length=0,c=a.kl-1,d=RH(a)):(c=b.F,d=b.Ch):(c=a.kl++,d=RH(a));var e=a.Jn.clone();g.wE(e,"SID",a.o);g.wE(e,"RID",c);g.wE(e,"AID",a.Yi);SH(a,e);c=new WG(a,0,a.o,c,a.vk+1);c.nh=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Wc=c;ZG(c,e,d)};SH=function(a,b){if(a.xc){var c=a.xc.ky(a);c&&g.La(c,function(a,c){g.wE(b,c,a)})}};
RH=function(a){var b=Math.min(a.g.length,1E3),c=["count="+b],d;6<a.Zg&&0<b?(d=a.g[0].b,c.push("ofs="+d)):d=0;for(var e=0;e<b;e++){var f=a.g[e].b,k=a.g[e].map,f=6>=a.Zg?e:f-d;try{g.zE(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.g.splice(0,b));return c.join("&")};VH=function(a){a.Kb||a.Ye||(a.C=1,a.Ye=nH((0,g.x)(a.iB,a),0),a.fi=0)};
XH=function(a){if(a.Kb||a.Ye||3<=a.fi)return!1;a.C++;a.Ye=nH((0,g.x)(a.iB,a),WH(a,a.fi));a.fi++;return!0};xH=function(a,b,c){a.Qp=c;a.ee=b.ff;a.GI(1,0);a.Jn=vH(a,null,a.bs);OH(a)};MH=function(a){null!=a.dh&&(g.ba.clearTimeout(a.dh),a.dh=null)};WH=function(a,b){var c=5E3+Math.floor(1E4*Math.random());a.Gb()||(c*=2);return c*b};
ZH=function(a,b){if(2==b||9==b){var c=null;a.xc&&(c=null);var d=(0,g.x)(a.AR,a);c||(c=new g.yg("//www.google.com/images/cleardot.gif"),AE(c));rH(c.toString(),1E4,d)}else cH();YH(a,b)};YH=function(a,b){a.b=0;a.xc&&a.xc.mx(a,b);$H(a);NH(a)};$H=function(a){a.b=0;a.ee=-1;if(a.xc)if(0==a.A.length&&0==a.g.length)a.xc.Yq(a);else{var b=g.Ia(a.A),c=g.Ia(a.g);a.A.length=0;a.g.length=0;a.xc.Yq(a,b,c)}};
vH=function(a,b,c){var d=g.uq(c);if(""!=d.g)b&&g.Ag(d,b+"."+d.g),g.Bg(d,d.D);else var e=window.location,d=Kja(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c);a.zk&&g.La(a.zk,function(a,b){g.wE(d,b,a)});g.wE(d,"VER",a.Zg);SH(a,d);return d};nH=function(a,b){if(!g.ia(a))throw Error("Fn must not be null and must be a function");return g.ba.setTimeout(function(){a()},b)};cH=function(){aI.U(new JH(aI))};bI=function(){};
cI=function(a,b){g.aF.call(this);this.B=0;if(g.ia(a))b&&(a=(0,g.x)(a,b));else if(a&&g.ia(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.D=a;g.ed(this,"tick",(0,g.x)(this.C,this));this.stop();g.bF(this,5E3+2E4*Math.random())};dI=function(a,b){this.K=a;this.A=b;this.o=new g.yk;this.g=new cI(this.pS,this);this.b=null;this.H=!1;this.C=null;this.G="";this.F=this.B=0;this.D=[]};
ika=function(a){return{firstTestResults:[""],secondTestResults:!a.b.Qp,sessionId:a.b.o,arrayId:a.b.Yi}};jka=function(a,b){(a.A.loungeIdToken=b)||a.g.stop()};
g.eI=function(a,b,c){g.Vw.call(this);this.B=window.NaN;this.L=!1;this.F=this.D=this.K=this.G=window.NaN;this.M=[];this.o=this.sa=this.b=null;this.ea=a;this.M.push(g.sh(window,"beforeunload",(0,g.x)(this.uJ,this)));this.g=[];this.sa=new g.sG;3==c["mdx-version"]&&(this.sa.o="RQ"+b.token);this.P=b.id;this.b=kka(this,c);this.b.subscribe("handlerOpened",this.hN,this);this.b.subscribe("handlerClosed",this.dN,this);this.b.subscribe("handlerError",this.eN,this);this.sa.o?this.b.subscribe("handlerMessage",
this.fN,this):this.b.subscribe("handlerMessage",this.gN,this);jka(this.b,b.token);this.subscribe("remoteQueueChange",function(){var a=this.sa.videoId;g.JE()&&g.xo("yt-remote-session-video-id",a)},this)};kka=function(a,b){return new dI(a.ea.lh("/bc",void 0,!1),b)};fI=function(a,b){a.publish("proxyStateChange",b)};lka=function(a){a.B=(0,g.Ad)((0,g.x)(function(){this.dc("Connecting timeout");this.A(1)},a),2E4)};gI=function(a){g.Bd(a.B);a.B=window.NaN};hI=function(a){g.Bd(a.G);a.G=window.NaN};
kI=function(a){iI(a);a.K=(0,g.Ad)((0,g.x)(function(){jI(this,"getNowPlaying")},a),2E4)};iI=function(a){g.Bd(a.K);a.K=window.NaN};lI=function(a){var b=a.b;return!!b.b&&3==b.b.getState()&&(0,window.isNaN)(a.B)};nI=function(a,b){b&&(gI(a),hI(a));b==lI(a)?b&&(fI(a,1),jI(a,"getSubtitlesTrack")):b?(a.H()&&a.sa.reset(),fI(a,1),jI(a,"getNowPlaying"),mI(a)):a.A(1)};mka=function(a,b){var c=b.ya.videoId;delete b.ya.videoId;c==a.sa.videoId&&(g.Mq(b.ya)?a.sa.A=null:a.sa.A=b.ya,a.publish("remotePlayerChange"))};
oI=function(a,b){var c=b.ya.videoId||b.ya.video_id,d=(0,window.parseInt)(b.ya.currentIndex,10);a.sa.o=b.ya.listId||a.sa.o;var e=a.sa,f=e.videoId;e.videoId=c;e.index=d;c!=f&&uG(e);a.publish("remoteQueueChange")};nka=function(a,b){b.ya=b.ya||{};oI(a,b);pI(a,b)};
pI=function(a,b){var c=(0,window.parseInt)(b.ya.currentTime||b.ya.current_time,10);g.xG(a.sa,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.ya.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.sa.b&&(c=-1E3);a.sa.b=c;1==a.sa.b?kI(a):iI(a);a.publish("remotePlayerChange")};oka=function(a,b){var c="true"==b.ya.muted;a.sa.volume=(0,window.parseInt)(b.ya.volume,10);a.sa.muted=c;a.publish("remotePlayerChange")};
pka=function(a,b){switch(b.action){case "loungeStatus":var c=g.Kd(b.ya.devices);a.g=(0,g.N)(c,function(a){return new mF(a)});break;case "loungeScreenDisconnected":qF(a.g,function(a){return"LOUNGE_SCREEN"==a.type});break;case "remoteConnected":var d=new mF(g.Kd(b.ya.device));g.io(a.g,function(a){return a.Wa(d)})||g.rF(a.g,d);break;case "remoteDisconnected":d=new mF(g.Kd(b.ya.device)),qF(a.g,function(a){return a.Wa(d)})}};
qka=function(a,b){var c=!1;if("loungeStatus"==b.action)c=!!g.io(a.g,function(a){return"LOUNGE_SCREEN"==a.type});else if("loungeScreenConnected"==b.action)c=!0;else if("loungeScreenDisconnected"==b.action)c=!1;else return;if(!(0,window.isNaN)(a.G))if(c)hI(a);else return;c==lI(a)?c&&fI(a,1):c?(gI(a),a.H()&&a.sa.reset(),fI(a,1),jI(a,"getNowPlaying"),mI(a)):a.A(1)};mI=function(a){g.Bd(a.F);a.F=(0,g.Ad)((0,g.x)(a.A,a,1),864E5)};
jI=function(a,b,c){c?a.dc("Sending: action="+b+", params="+g.Nd(c)):a.dc("Sending: action="+b);a.b.sendMessage(b,c)};g.qI=function(a){this.g=a||window;this.b=[]};xE=[];g.mz.prototype.seek=g.T(107,function(){});g.Yx.prototype.Mb=g.T(99,function(){return g.Y(this,8)&&!g.Y(this,64)&&!g.Y(this,2)});g.qx.prototype.Vi=g.T(78,function(){return 1==this.C});g.Vw.prototype.ab=g.T(37,function(a,b,c){return this.ha()?!1:vE(this.Z,a,b,c)});g.y(g.CE,g.E);g.h=g.CE.prototype;
g.h.listen=function(a,b,c,d){return g.yE(this,a,b,c,d)};g.h.Ia=function(a,b,c,d,e){if(g.ea(b))for(var f=0;f<b.length;f++)this.Ia(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.A||this,c=g.fd(c),d=!!d,b=g.Yc(a)?g.dd(a.P,String(b),c,d,e):a?(a=g.id(a))?g.dd(a,b,c,d,e):null:null,b&&(g.od(b),delete this.g[b.key]);return this};g.h.removeAll=function(){g.La(this.g,function(a,b){this.g.hasOwnProperty(b)&&g.od(a)},this);this.g={}};g.h.O=function(){g.CE.J.O.call(this);this.removeAll()};
g.h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var KE="";g.y(NE,g.Gd);NE.prototype.set=function(a,b){this.g.set(this.b+a,b)};NE.prototype.get=function(a){return this.g.get(this.b+a)};NE.prototype.remove=function(a){this.g.remove(this.b+a)};NE.prototype.ed=function(a){var b=this.g.ed(!0),c=this,d=new g.wb;d.next=function(){for(var d=b.next();d.substr(0,c.b.length)!=c.b;)d=b.next();return a?d.substr(c.b.length):c.g.get(d)};return d};var cF;
YE.prototype.toString=function(){return"{id:"+this.id+",name:"+this.name+",activityId:"+this.b+",status:"+this.status+"}"};var Oja={EV:"atp",uZ:"ska",YY:"que",rY:"mus",qZ:"sus"},jH={"'":"\\'"},kH={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"};g.y(g.aF,g.td);g.h=g.aF.prototype;g.h.enabled=!1;g.h.Nd=null;
g.h.mJ=function(){if(this.enabled){var a=(0,g.G)()-this.A;0<a&&a<.8*this.b?this.Nd=this.g.setTimeout(this.o,this.b-a):(this.Nd&&(this.g.clearTimeout(this.Nd),this.Nd=null),this.U("tick"),this.enabled&&(this.Nd=this.g.setTimeout(this.o,this.b),this.A=(0,g.G)()))}};g.h.start=function(){this.enabled=!0;this.Nd||(this.Nd=this.g.setTimeout(this.o,this.b),this.A=(0,g.G)())};g.h.stop=function(){this.enabled=!1;this.Nd&&(this.g.clearTimeout(this.Nd),this.Nd=null)};
g.h.O=function(){g.aF.J.O.call(this);this.stop();delete this.g};mF.prototype.Wa=function(a){return a?this.id==a.id:!1};g.h=g.sF.prototype;g.h.Cb=function(){return this.b.length+this.g.length};g.h.Ua=function(){return g.Fo(this.b)&&g.Fo(this.g)};g.h.clear=function(){this.b=[];this.g=[]};g.h.contains=function(a){return g.Ea(this.b,a)||g.Ea(this.g,a)};g.h.remove=function(a){var b=(0,g.oca)(this.b,a);if(0>b)return g.Ga(this.g,a);g.Fa(this.b,b);return!0};
g.h.jb=function(){for(var a=[],b=this.b.length-1;0<=b;--b)a.push(this.b[b]);for(var c=this.g.length,b=0;b<c;++b)a.push(this.g[b]);return a};var rI,sI,rka,tI,ska,uI,tka,wF;g.yF=window.document.currentScript&&-1!=window.document.currentScript.src.indexOf("?loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js";rI=0<window.location.hash.indexOf("__CastInternalExtensionIds__");sI=["boadgeojelhgndaghljhdicfkmllpafd","dliochdbjfkdbacpmhlcpmleaejidimm"];rka=["hfaagokkkhdbgiakmmlclaapfelnkoah","fmfcbgogabcbclcofgocippekhfcmgfj","enhhojjnijigcajfphajepfemndkmdlo","eojlgccfgnjlphjnlopmadngcgmmdgpk"];tI=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","fjhoaacokmgbjemoflkofnenfaiekifl"];
ska=["ekpaaapppgpmolpcldedioblbkmijaca","lhkfccafpkdlaodkicmokbmfapjadkij","ibiljbkambkbohapfhoonkcpcikdglop","enhhojjnijigcajfphajepfemndkmdlo"];uI=rI?sI.concat(rka):sI;tka=rI?ska.concat(tI):tI;wF=window.navigator.presentation?uI.concat(tka):uI;var Sja=(0,g.G)(),AF=null,FF=Array(50),EF=-1,GF=!1;g.y(g.HF,g.Vw);g.HF.prototype.zd=function(){return this.b};g.HF.prototype.contains=function(a){return!!g.iF(this.b,a)};g.HF.prototype.get=function(a){return a?g.hF(this.b,a):null};g.y(KF,g.Vw);var vI=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=KF.prototype;g.h.start=function(){!this.b&&(0,window.isNaN)(this.g)&&this.kD()};g.h.stop=function(){this.b&&(this.b.abort(),this.b=null);(0,window.isNaN)(this.g)||(g.Bd(this.g),this.g=window.NaN)};g.h.O=function(){this.stop();KF.J.O.call(this)};
g.h.kD=function(){this.g=window.NaN;this.b=g.ye(this.D.lh("/pairing/get_screen"),{method:"POST",Sd:{pairing_code:this.C},timeout:5E3,rb:(0,g.x)(this.uS,this),onError:(0,g.x)(this.tS,this),ke:(0,g.x)(this.vS,this)})};g.h.uS=function(a,b){this.b=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.publish("pairingComplete",new ME(c))};
g.h.tS=function(a){this.b=null;a.status&&404==a.status?this.o>=vI.length?this.publish("pairingFailed",Error("DIAL polling timed out")):(a=vI[this.o],this.g=(0,g.Ad)((0,g.x)(this.kD,this),a),this.o++):this.publish("pairingFailed",Error("Server error "+a.status))};g.h.vS=function(){this.b=null;this.publish("pairingFailed",Error("Server not responding"))};g.y(MF,g.HF);g.h=MF.prototype;g.h.start=function(){LF(this)&&this.publish("screenChange");!g.qo("yt-remote-lounge-token-expiration")&&NF(this);g.Bd(this.g);this.g=(0,g.Ad)((0,g.x)(this.start,this),1E4)};g.h.pm=function(a,b){LF(this);IF(this,a);OF(this,!1);this.publish("screenChange");b(a);a.token||NF(this)};g.h.remove=function(a,b){var c=LF(this);Uja(this,a)&&(OF(this,!1),c=!0);b(a);c&&this.publish("screenChange")};
g.h.em=function(a,b,c,d){var e=LF(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,OF(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.publish("screenChange")};g.h.O=function(){g.Bd(this.g);MF.J.O.call(this)};g.h.EJ=function(a){LF(this);var b=this.b.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}OF(this,!b);b&&g.DF(this.D,"Missed "+b+" lounge tokens.")};
g.h.DJ=function(a){g.DF(this.D,"Requesting lounge tokens failed: "+a)};g.y(QF,g.Vw);g.h=QF.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.qo("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?TF(this):(this.A=(0,g.G)()+3E5,g.xo("yt-remote-fast-check-period",this.A),this.pu())};g.h.Ua=function(){return g.Mq(this.b)};g.h.update=function(){PF("Updating availability on schedule.");var a=this.B(),b=g.Ma(this.b,function(b,d){return b&&!!g.hF(a,d)},this);SF(this,b)};
g.h.O=function(){g.Bd(this.o);this.o=window.NaN;this.g&&(this.g.abort(),this.g=null);QF.J.O.call(this)};g.h.pu=function(){g.Bd(this.o);this.o=window.NaN;this.g&&this.g.abort();var a=UF(this);if(g.Eo(a)){var b=this.C.lh("/pairing/get_screen_availability");this.g=this.C.sendRequest("POST",b,{lounge_token:g.Oa(a).join(",")},(0,g.x)(this.XO,this,a),(0,g.x)(this.WO,this))}else SF(this,{}),TF(this)};
g.h.XO=function(a,b){this.g=null;var c=g.Oa(UF(this));if(g.$E(c,g.Oa(a))){for(var c=b.screens||[],d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;SF(this,d);TF(this)}else this.Ab("Changing Screen set during request."),this.pu()};g.h.WO=function(a){this.Ab("Screen availability failed: "+a);this.g=null;TF(this)};g.h.Ab=function(a){g.DF("OnlineScreenService",a)};g.y(g.VF,g.HF);g.h=g.VF.prototype;g.h.start=function(){this.o.start();this.g.start();this.b.length&&(this.publish("screenChange"),this.g.Ua()||this.publish("onlineScreenChange"))};g.h.pm=function(a,b,c){this.o.pm(a,b,c)};g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.g.update()};g.h.em=function(a,b,c,d){this.o.contains(a)?this.o.em(a,b,c,d):(a="Updating name of unknown screen: "+a.name,g.DF(this.D,a),d(Error(a)))};
g.h.zd=function(a){return a?this.b:g.Ha(this.b,(0,g.Ac)(this.A,function(a){return!this.contains(a)},this))};g.h.lD=function(){return(0,g.Ac)(this.zd(!0),function(a){return!!this.g.b[a.id]},this)};g.h.mD=function(a,b,c,d,e){JF(this,"getDialScreenByPairingCode "+a+" / "+b);var f=new KF(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(a){g.Sc(f);d(WF(this,a))},this));f.subscribe("pairingFailed",function(a){g.Sc(f);e(a)});f.start();return(0,g.x)(f.stop,f)};
g.h.kJ=function(a,b){for(var c=2,d=b(a,c);YF(this,d);){c++;if(20<c)return a;d=b(a,c)}return d};g.h.xS=function(a,b,c,d){g.ye(this.C.lh("/pairing/get_screen"),{method:"POST",Sd:{pairing_code:a},timeout:5E3,rb:(0,g.x)(function(a,d){var k=new ME(d.screen||{});if(!k.name||YF(this,k.name))k.name=this.kJ(k.name,b);c(WF(this,k))},this),onError:(0,g.x)(function(a){d(Error("pairing request failed: "+a.status))},this),ke:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.O=function(){g.Sc(this.o);g.Sc(this.g);g.VF.J.O.call(this)};g.h.IJ=function(){ZF(this);this.publish("screenChange");this.g.update()};g.VF.prototype.dispose=g.VF.prototype.dispose;g.y(aG,g.Vw);g.h=aG.prototype;g.h.Ro=function(a){this.o=a;this.publish("sessionScreen",this.o)};g.h.od=function(a){this.ha()||(a&&cG(this,""+a),this.o=null,this.publish("sessionScreen",null))};g.h.oD=function(){return null};
g.h.Cu=function(a){var b=this.g;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){bG(this,"Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){cG(this,"Failed to update receiver status for: "+b.friendlyName)},this))};g.h.O=function(){this.Cu("");aG.J.O.call(this)};g.y(eG,aG);g.h=eG.prototype;g.h.Bu=function(a){if(this.b){if(this.b==a)return;cG(this,"Overriding cast sesison with new session object");this.b.removeUpdateListener(this.D);this.b.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C)}this.b=a;this.b.addUpdateListener(this.D);this.b.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.C);this.A&&gG(this);fG(this,"getMdxSessionStatus")};g.h.Zi=function(a){bG(this,"launchWithParams: "+g.Nd(a));this.A=a;this.b&&gG(this)};
g.h.stop=function(){this.b?this.b.stop((0,g.x)(function(){this.od()},this),(0,g.x)(function(){this.od(Error("Failed to stop receiver app."))},this)):this.od(Error("Stopping cast device witout session."))};g.h.Cu=g.u;g.h.O=function(){bG(this,"disposeInternal");g.Bd(this.B);this.B=0;this.b&&(this.b.removeUpdateListener(this.D),this.b.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C));this.b=null;eG.J.O.call(this)};
g.h.QP=function(a,b){if(!this.ha())if(b){var c=g.Ld(b);if(c){var d=""+c.type,c=c.data||{};bG(this,"onYoutubeMessage_: "+d+" "+g.Nd(c));switch(d){case "mdxSessionStatus":dG(this,c.screenId);break;default:cG(this,"Unknown youtube message: "+d)}}else cG(this,"Unable to parse message.")}else cG(this,"No data in message.")};
g.h.oy=function(a,b,c,d){XF(this.G,this.g.label,a,this.g.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(cG(this,"Screen "+a+" appears to be offline. "+d+" retries left."),(0,g.Ad)((0,g.x)(this.oy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};g.h.oD=function(){return this.b};g.h.yS=function(a){this.ha()||a||(cG(this,"Cast session died."),this.od())};g.y(hG,aG);g.h=hG.prototype;g.h.Bu=function(a){this.B=a;this.B.addUpdateListener(this.K)};g.h.Zi=function(a){this.A=a;this.D()};g.h.stop=function(){this.b();this.b=g.u;g.Bd(this.C);this.B?this.B.stop((0,g.x)(this.od,this,null),(0,g.x)(this.od,this,"Failed to stop DIAL device.")):this.od()};g.h.O=function(){this.b();this.b=g.u;g.Bd(this.C);this.B&&this.B.removeUpdateListener(this.K);this.B=null;hG.J.O.call(this)};g.h.BS=function(a){this.ha()||a||(cG(this,"DIAL session died."),this.b(),this.b=g.u,this.od())};
g.h.Rs=function(a){this.H=GE();if(this.A){var b=new window.chrome.cast.DialLaunchResponse(!0,jG(this));a(b);iG(this)}else this.D=(0,g.x)(function(){g.Bd(this.C);this.D=g.u;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,jG(this));a(b);iG(this)},this),this.C=(0,g.Ad)((0,g.x)(function(){this.D()},this),100)};
g.h.hL=function(a,b){XF(this.G,this.F.receiver.label,a,this.g.friendlyName,(0,g.x)(function(a){a&&a.token?(this.Ro(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Rs(b)},this),(0,g.x)(function(a){cG(this,"Failed to get DIAL screen: "+a);this.Rs(b)},this))};g.y(kG,aG);kG.prototype.stop=function(){this.od()};kG.prototype.Bu=g.u;kG.prototype.Zi=function(){g.Bd(this.b);this.b=window.NaN;var a=g.hF(this.G.zd(),this.g.label);a?this.Ro(a):this.od(Error("No such screen"))};kG.prototype.O=function(){g.Bd(this.b);this.b=window.NaN;kG.J.O.call(this)};g.y(g.lG,g.Vw);g.h=g.lG.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest("233637DE");c.dialRequest=new window.chrome.cast.DialRequest("YouTube");var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION,c=new window.chrome.cast.ApiConfig(c,(0,g.x)(this.eB,this),(0,g.x)(this.LO,this),d,e);c.customDialLaunchCallback=(0,g.x)(this.AN,this);window.chrome.cast.initialize(c,
(0,g.x)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),CF(oG),this.g.subscribe("onlineScreenChange",(0,g.x)(this.nD,this)),this.o=rG(this),window.chrome.cast.setCustomReceivers(this.o,g.u,(0,g.x)(function(a){this.Ab("Failed to set initial custom receivers: "+g.Nd(a))},this)),this.publish("yt-remote-cast2-availability-change",pG(this)),b(!0))},this),(0,g.x)(function(a){this.Ab("Failed to initialize API: "+g.Nd(a));b(!1)},this))};
g.h.WQ=function(a,b){nG("Setting connected screen ID: "+a+" -> "+b);if(this.b){var c=this.b.o;if(!a||c&&c.id!=a)nG("Unsetting old screen status: "+this.b.g.friendlyName),g.Sc(this.b),this.b=null}if(a&&b){if(!this.b){c=g.hF(this.g.zd(),a);if(!c){nG("setConnectedScreenStatus: Unknown screen.");return}var d=mG(this,c);d||(nG("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,
this.o.push(d),window.chrome.cast.setCustomReceivers(this.o,g.u,(0,g.x)(function(a){this.Ab("Failed to set initial custom receivers: "+g.Nd(a))},this)));nG("setConnectedScreenStatus: new active receiver: "+d.friendlyName);qG(this,new kG(this.g,d),!0)}this.b.Cu(b)}else nG("setConnectedScreenStatus: no screen.")};g.h.XQ=function(a){this.ha()?this.Ab("Setting connection data on disposed cast v2"):this.b?this.b.Zi(a):this.Ab("Setting connection data without a session")};
g.h.AS=function(){this.ha()?this.Ab("Stopping session on disposed cast v2"):this.b?(this.b.stop(),g.Sc(this.b),this.b=null):nG("Stopping non-existing session")};g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.x)(this.eB,this),(0,g.x)(this.cP,this))};
g.h.O=function(){this.g.ab("onlineScreenChange",(0,g.x)(this.nD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);var a=oG,b=g.r("yt.mdx.remote.debug.handlers_");g.Ga(b||[],a);g.Sc(this.b);g.lG.J.O.call(this)};g.h.Ab=function(a){g.DF("Controller",a)};g.h.fB=function(a,b){this.b==a&&(b||qG(this,null),this.publish("yt-remote-cast2-session-change",b))};
g.h.JO=function(a,b){if(!this.ha())if(a)switch(nG("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.b)if(this.b.g.label!=a.label)nG("onReceiverAction_: Stopping active receiver: "+this.b.g.friendlyName),this.b.stop();else{nG("onReceiverAction_: Casting to active receiver.");this.b.o&&this.publish("yt-remote-cast2-session-change",this.b.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:qG(this,new kG(this.g,a));
break;case window.chrome.cast.ReceiverType.DIAL:qG(this,new hG(this.g,a));break;case window.chrome.cast.ReceiverType.CAST:qG(this,new eG(this.g,a));break;default:this.Ab("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.b&&this.b.g.label==a.label?this.b.stop():this.Ab("Stopping receiver w/o session: "+a.friendlyName)}else this.Ab("onReceiverAction_ called without receiver.")};
g.h.AN=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Ab("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.b?this.b.g:null;if(!c||c.label!=b.label)return this.Ab("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.b.o)return nG("Reselecting dial screen."),
this.publish("yt-remote-cast2-session-change",this.b.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Ab('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);qG(this,new hG(this.g,b))}b=this.b;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.x)(b.hL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.x)(b.Rs,b))};
g.h.eB=function(a){if(!this.ha()){nG("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.b)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)nG("Got resumed cast session before resumed mdx connection."),qG(this,new eG(this.g,b),!0);else{this.Ab("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.b.g,d=g.hF(this.g.zd(),c.label);d&&g.XE(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&
b.receiverType==window.chrome.cast.ReceiverType.CAST&&(nG("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Sc(this.b),this.b=new eG(this.g,b),this.b.subscribe("sessionScreen",(0,g.x)(this.fB,this,this.b)),this.b.Zi(null));this.b.Bu(a)}}};g.h.zS=function(){return this.b?this.b.oD():null};g.h.cP=function(a){this.ha()||(this.Ab("Failed to estabilish a session: "+g.Nd(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&qG(this,null))};
g.h.LO=function(a){nG("Receiver availability updated: "+a);if(!this.ha()){var b=pG(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;pG(this)!=b&&this.publish("yt-remote-cast2-availability-change",pG(this))}};
g.h.nD=function(){if(!this.ha()){var a=pG(this);this.o=rG(this);nG("Updating custom receivers: "+g.Nd(this.o));window.chrome.cast.setCustomReceivers(this.o,g.u,(0,g.x)(function(){this.Ab("Failed to set custom receivers.")},this));var b=pG(this);b!=a&&this.publish("yt-remote-cast2-availability-change",b)}};g.lG.prototype.setLaunchParams=g.lG.prototype.XQ;g.lG.prototype.setConnectedScreenStatus=g.lG.prototype.WQ;g.lG.prototype.stopSession=g.lG.prototype.AS;g.lG.prototype.getCastSession=g.lG.prototype.zS;
g.lG.prototype.requestSession=g.lG.prototype.requestSession;g.lG.prototype.init=g.lG.prototype.init;g.lG.prototype.dispose=g.lG.prototype.dispose;g.sG.prototype.reset=function(a){this.g=[];this.o="";g.vG(this);this.volume=-1;this.muted=!1;a&&(this.g=a.videoIds,this.index=a.index,this.o=a.listId,this.videoId=a.videoId,this.b=a.playerState,this.volume=a.volume,this.muted=a.muted,this.D=a.audioTrackId,this.A=a.trackData,this.B=a.playerTime,this.C=a.playerTimeAt)};g.sG.prototype.Mb=function(){return 1==this.b};g.sG.prototype.remove=function(a){g.tG(this,"remove");var b=g.wG(this);return g.Ga(this.g,a)?(this.index=(0,g.Da)(this.g,b),!0):!1};
g.sG.prototype.clone=function(){return new g.sG(g.CG(this))};var FG=!1,GG=g.r("yt.mdx.remote.castapi.devices_")||[];g.q("yt.mdx.remote.castapi.devices_",GG,void 0);MG.prototype.parse=function(a){return this.b(a)};g.y(g.NG,g.E);g.h=g.NG.prototype;g.h.uj=!1;g.h.yl=0;g.h.mh=null;g.h.$r=function(a){this.b=arguments;this.mh||this.yl?this.uj=!0:g.OG(this)};g.h.stop=function(){this.mh&&(g.Sw(this.mh),this.mh=null,this.uj=!1,this.b=[])};g.h.pause=function(){this.yl++};g.h.resume=g.m(109);g.h.O=function(){g.NG.J.O.call(this);this.stop()};g.h.kP=function(){this.mh=null;this.uj&&!this.yl&&(this.uj=!1,g.OG(this))};RG.prototype.b=null;var wI;g.y(UG,RG);wI=new UG;g.h=WG.prototype;g.h.nh=null;g.h.re=!1;g.h.Kj=null;g.h.Av=null;g.h.Jl=null;g.h.Di=null;g.h.Yf=null;g.h.qg=null;g.h.Ch=null;g.h.Sb=null;g.h.lm=0;g.h.te=null;g.h.Tp=null;g.h.oh=null;g.h.Bk=-1;g.h.aC=!0;g.h.Yg=!1;g.h.hs=0;g.h.cp=null;var eH={},bH={};g.h=WG.prototype;g.h.setTimeout=function(a){this.B=a};g.h.sQ=function(a){a=a.target;var b=this.cp;b&&3==EH(a)?b.$r():this.hD(a)};
g.h.hD=function(a){try{if(a==this.Sb)a:{var b=EH(this.Sb),c=this.Sb.g,d=this.Sb.getStatus();if(!XG()||g.Ib&&!g.Mb("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Uc&&!g.HH(this.Sb))break a;this.Yg||4!=b||7==c||(8==c||0>=d?this.b.je(3):this.b.je(2));oH(this);var e=this.Sb.getStatus();this.Bk=e;var f=g.HH(this.Sb);(this.re=200==e)?(4==b&&gH(this),this.C?(iH(this,b,f),g.Uc&&this.re&&3==b&&(this.A.listen(this.g,"tick",this.fQ),this.g.start())):(dH(f),fH(this,f)),this.re&&!this.Yg&&(4==b?this.b.Oo(this):
(this.re=!1,aH(this)))):(this.oh=400==e&&0<f.indexOf("Unknown SID")?3:0,cH(),gH(this),hH(this))}}catch(k){this.Sb&&g.HH(this.Sb)&&g.HH(this.Sb)}finally{}};g.h.fQ=function(){var a=EH(this.Sb),b=g.HH(this.Sb);this.lm<b.length&&(oH(this),iH(this,a,b),this.re&&4!=a&&aH(this))};g.h.tP=function(a){nH((0,g.x)(this.sP,this,a),0)};g.h.sP=function(a){this.Yg||(dH(a),oH(this),fH(this,a),aH(this))};g.h.oB=function(a){nH((0,g.x)(this.rP,this,a),0)};
g.h.rP=function(a){this.Yg||(gH(this),this.re=a,this.b.Oo(this),this.b.je(4))};g.h.cancel=function(){this.Yg=!0;gH(this)};g.h.MP=function(){this.Kj=null;var a=(0,g.G)();0<=a-this.Av?(2!=this.Di&&this.b.je(3),gH(this),this.oh=2,cH(),hH(this)):mH(this,this.Av-a)};g.h=uH.prototype;g.h.ds=null;g.h.rd=null;g.h.fp=!1;g.h.ty=null;g.h.Hn=null;g.h.es=null;g.h.gs=null;g.h.Od=null;g.h.ff=-1;g.h.Ak=null;g.h.fk=null;g.h.connect=function(a){this.gs=a;a=vH(this.b,null,this.gs);cH();this.ty=(0,g.G)();var b=this.b.F;null!=b?(this.Ak=b[0],(this.fk=b[1])?(this.Od=1,wH(this)):(this.Od=2,yH(this))):(BE(a,"MODE","init"),this.rd=new WG(this,0,void 0,void 0,void 0),this.rd.nh=this.ds,$G(this.rd,a,!1,null,!0),this.Od=0)};
g.h.QH=function(a){if(a)this.Od=2,yH(this);else{cH();var b=this.b;b.ee=b.Lf.ff;ZH(b,9)}a&&this.je(2)};g.h.sr=function(a){return this.b.sr(a)};g.h.sy=function(){return!1};
g.h.aB=function(a,b){this.ff=a.Bk;if(0==this.Od)if(b){try{var c=this.g.parse(b)}catch(d){c=this.b;c.ee=this.ff;ZH(c,2);return}this.Ak=c[0];this.fk=c[1]}else c=this.b,c.ee=this.ff,ZH(c,2);else if(2==this.Od)if(this.fp)cH(),this.es=(0,g.G)();else if("11111"==b){if(cH(),this.fp=!0,this.Hn=(0,g.G)(),c=this.Hn-this.ty,XG()||500>c)this.ff=200,this.rd.cancel(),cH(),xH(this.b,this,!0)}else cH(),this.Hn=this.es=(0,g.G)(),this.fp=!1};
g.h.Oo=function(){this.ff=this.rd.Bk;if(this.rd.re)0==this.Od?this.fk?(this.Od=1,wH(this)):(this.Od=2,yH(this)):2==this.Od&&(a=!1,(a=XG()?this.fp:200>this.es-this.Hn?!1:!0)?(cH(),xH(this.b,this,!0)):(cH(),xH(this.b,this,!1)));else{0==this.Od?cH():2==this.Od&&cH();var a=this.b;a.ee=this.ff;ZH(a,2)}};g.h.Ql=function(){return this.b.Ql()};g.h.Gb=function(){return this.b.Gb()};g.h.je=function(a){this.b.je(a)};g.y(g.zH,g.td);var gka=/^https?$/i,uka=["POST","PUT"];g.h=g.zH.prototype;
g.h.send=function(a,b,c,d){if(this.b)throw Error("[goog.net.XhrIo] Object is active with another request="+this.G+"; newUri="+a);b=b?b.toUpperCase():"GET";this.G=a;this.C="";this.g=0;this.S=b;this.M=!1;this.o=!0;this.b=this.L?VG(this.L):VG(wI);this.K=this.L?TG(this.L):TG(wI);this.b.onreadystatechange=(0,g.x)(this.ZA,this);try{oF(DH(this,"Opening Xhr")),this.N=!0,this.b.open(b,String(a),!0),this.N=!1}catch(f){oF(DH(this,"Error opening Xhr: "+f.message));CH(this,f);return}a=c||"";var e=this.headers.clone();
d&&g.zE(d,function(a,b){e.set(b,a)});d=g.io(e.qb(),fka);c=g.ba.FormData&&a instanceof g.ba.FormData;!g.Ea(uka,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.b.setRequestHeader(b,a)},this);this.X&&(this.b.responseType=this.X);g.no(this.b,"withCredentials")&&(this.b.withCredentials=this.R);try{GH(this),0<this.B&&(this.H=eka(this.b),oF(DH(this,"Will abort after "+this.B+"ms if incomplete, xhr2 "+this.H)),this.H?(this.b.timeout=this.B,this.b.ontimeout=
(0,g.x)(this.uy,this)):this.D=g.Rw(this.uy,this.B,this)),oF(DH(this,"Sending request")),this.F=!0,this.b.send(a),this.F=!1}catch(f){oF(DH(this,"Send error: "+f.message)),CH(this,f)}};g.h.uy=function(){"undefined"!=typeof g.Zl&&this.b&&(this.C="Timed out after "+this.B+"ms, aborting",this.g=8,DH(this,this.C),this.U("timeout"),pH(this,8))};g.h.O=function(){this.b&&(this.o&&(this.o=!1,this.A=!0,this.b.abort(),this.A=!1),BH(this,!0));g.zH.J.O.call(this)};
g.h.ZA=function(){this.ha()||(this.N||this.F||this.A?FH(this):this.IO())};g.h.IO=function(){FH(this)};g.h.Gb=function(){return!!this.b};g.h.getStatus=function(){try{return 2<EH(this)?this.b.status:-1}catch(a){return-1}};g.h=IH.prototype;g.h.zk=null;g.h.Wc=null;g.h.Kb=null;g.h.bs=null;g.h.Jn=null;g.h.$w=null;g.h.On=null;g.h.kl=0;g.h.qM=0;g.h.xc=null;g.h.Rf=null;g.h.Ye=null;g.h.dh=null;g.h.Lf=null;g.h.Qp=null;g.h.Yi=-1;g.h.Oz=-1;g.h.ee=-1;g.h.vk=0;g.h.fi=0;g.h.Zg=8;var aI=new g.td;g.y(JH,g.Tc);g.y(KH,g.Tc);g.y(LH,g.Tc);g.h=IH.prototype;g.h.connect=function(a,b,c,d,e){cH();this.bs=b;this.zk=c||{};d&&g.n(e)&&(this.zk.OSID=d,this.zk.OAID=e);this.Lf=new uH(this,this.G);this.Lf.ds=null;this.Lf.g=this.B;this.Lf.connect(a)};
g.h.disconnect=function(){NH(this);if(3==this.b){var a=this.kl++,b=this.Jn.clone();g.wE(b,"SID",this.o);g.wE(b,"RID",a);g.wE(b,"TYPE","terminate");SH(this,b);a=new WG(this,0,this.o,a,void 0);a.Di=2;a.Yf=AE(b.clone());(new window.Image).src=a.Yf;a.Jl=(0,g.G)();aH(a)}$H(this)};g.h.sy=function(){return 0==this.b};g.h.getState=function(){return this.b};g.h.jB=function(a){this.Rf=null;UH(this,a)};
g.h.iB=function(){this.Ye=null;this.Kb=new WG(this,0,this.o,"rpc",this.C);this.Kb.nh=null;this.Kb.hs=0;var a=this.$w.clone();g.wE(a,"RID","rpc");g.wE(a,"SID",this.o);g.wE(a,"CI",this.Qp?"0":"1");g.wE(a,"AID",this.Yi);SH(this,a);if(XG())g.wE(a,"TYPE","xmlhttp"),$G(this.Kb,a,!0,this.On,!1);else{g.wE(a,"TYPE","html");var b=this.Kb,c=!!this.On;b.Di=3;b.Yf=AE(a.clone());lH(b,c)}};
g.h.aB=function(a,b){if(0!=this.b&&(this.Kb==a||this.Wc==a))if(this.ee=a.Bk,this.Wc==a&&3==this.b)if(7<this.Zg){var c;try{c=this.B.parse(b)}catch(f){c=null}if(g.ea(c)&&3==c.length)if(0==c[0])a:{if(!this.Ye){if(this.Kb)if(this.Kb.Jl+3E3<this.Wc.Jl)MH(this),this.Kb.cancel(),this.Kb=null;else break a;XH(this);cH()}}else this.Oz=c[1],0<this.Oz-this.Yi&&37500>c[2]&&this.Qp&&0==this.fi&&!this.dh&&(this.dh=nH((0,g.x)(this.WM,this),6E3));else ZH(this,11)}else"y2f%"!=b&&ZH(this,11);else if(this.Kb==a&&MH(this),
!g.A(b)){c=this.B.parse(b);g.ea(c);for(var d=0;d<c.length;d++){var e=c[d];this.Yi=e[0];e=e[1];2==this.b?"c"==e[0]?(this.o=e[1],this.On=e[2],e=e[3],null!=e?this.Zg=e:this.Zg=6,this.b=3,this.xc&&this.xc.qx(this),this.$w=vH(this,this.Ql()?this.On:null,this.bs),VH(this)):"stop"==e[0]&&ZH(this,7):3==this.b&&("stop"==e[0]?ZH(this,7):"noop"!=e[0]&&this.xc&&this.xc.ox(this,e),this.fi=0)}}};g.h.WM=function(){null!=this.dh&&(this.dh=null,this.Kb.cancel(),this.Kb=null,XH(this),cH())};
g.h.Oo=function(a){var b;if(this.Kb==a)MH(this),this.Kb=null,b=2;else if(this.Wc==a)this.Wc=null,b=1;else return;this.ee=a.Bk;if(0!=this.b)if(a.re)1==b?((0,g.G)(),aI.U(new KH(aI,a.Ch?a.Ch.length:0)),OH(this),this.A.length=0):VH(this);else{var c=a.oh;if(!(3==c||7==c||0==c&&0<this.ee)){var d;if(d=1==b)this.Wc||this.Rf?d=!1:1==this.b||2<=this.vk?d=!1:(this.Rf=nH((0,g.x)(this.jB,this,a),WH(this,this.vk)),this.vk++,d=!0);if(d||2==b&&XH(this))return}switch(c){case 1:ZH(this,5);break;case 4:ZH(this,10);
break;case 3:ZH(this,6);break;case 7:ZH(this,12);break;default:ZH(this,2)}}};g.h.GI=function(a){if(!g.Ea(arguments,this.b))throw Error("Unexpected channel state: "+this.b);};g.h.AR=function(a){a?cH():(cH(),YH(this,8))};g.h.sr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.zH;a.R=!1;return a};g.h.Gb=function(){return!!this.xc&&this.xc.Gb(this)};g.h.je=function(){aI.U(new LH(aI))};g.h.Ql=function(){return!XG()};g.h=bI.prototype;g.h.qx=function(){};
g.h.ox=function(){};g.h.mx=function(){};g.h.Yq=function(){};g.h.ky=function(){return{}};g.h.Gb=function(){return!0};g.y(cI,g.aF);cI.prototype.C=function(){if(500<this.b){var a=this.b;24E4>2*a&&(a*=2);g.bF(this,a)}this.D()};cI.prototype.start=function(){cI.J.start.call(this);this.B=(0,g.G)()+this.b};cI.prototype.stop=function(){this.B=0;cI.J.stop.call(this)};g.y(dI,bI);g.h=dI.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};g.h.ab=function(a,b,c){return vE(this.o,a,b,c)};g.h.xd=function(a){return this.o.xd(a)};g.h.publish=function(a,b){return this.o.publish.apply(this.o,arguments)};g.h.dispose=function(){this.H||(this.H=!0,this.o.clear(),this.disconnect(),g.Sc(this.o))};g.h.ha=function(){return this.H};
g.h.connect=function(a,b,c){if(!this.b||2!=this.b.getState()){this.G="";this.g.stop();this.C=a||null;this.B=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new IH("1",c?c.firstTestResults:null,c?c.secondTestResults:null),e=this.b;e&&(e.xc=null);d.xc=this;this.b=d;e?(3!=e.getState()&&0==QH(e)||e.getState(),this.b.connect(a,b,this.A,e.o,e.Yi)):c?this.b.connect(a,b,this.A,c.sessionId,c.arrayId):this.b.connect(a,b,this.A)}};
g.h.disconnect=function(a){this.F=a||0;this.g.stop();this.b&&(3==this.b.getState()&&UH(this.b),this.b.disconnect());this.F=0};g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Sa(c,b);this.g.enabled||2==(this.b?this.b.getState():0)?this.D.push(c):this.b&&3==this.b.getState()&&PH(this.b,c)};g.h.qx=function(){var a=this.g;a.stop();g.bF(a,5E3+2E4*Math.random());this.C=null;this.B=0;if(this.D.length){a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)PH(this.b,a[b])}this.publish("handlerOpened")};
g.h.mx=function(a,b){var c=2==b&&401==this.b.ee;if(4!=b&&!c){if(6==b||410==this.b.ee)c=this.g,c.stop(),g.bF(c,500);this.g.start()}this.publish("handlerError",b)};g.h.Yq=function(a,b,c){if(!this.g.enabled)this.publish("handlerClosed");else if(c)for(a=0,b=c.length;a<b;++a){var d=c[a].map;d&&this.D.push(d)}};g.h.ky=function(){var a={v:2};this.G&&(a.gsessionid=this.G);0!=this.B&&(a.ui=""+this.B);0!=this.F&&(a.ui=""+this.F);this.C&&g.Sa(a,this.C);return a};
g.h.ox=function(a,b){if("S"==b[0])this.G=b[1];else if("gracefulReconnect"==b[0]){var c=this.g;c.stop();g.bF(c,500);this.g.start();this.b.disconnect()}else this.publish("handlerMessage",new Yja(b[0],b[1]))};g.h.getDeviceId=function(){return this.A.id};g.h.pS=function(){this.g.stop();0!=QH(this.b)?this.g.start():this.connect(this.C,this.B)};g.y(g.eI,g.Vw);g.h=g.eI.prototype;
g.h.connect=function(a,b){if(b){if(this.sa.o){var c=b.listId,d=b.videoId,e=b.index,f=b.currentTime||0;5>=f&&(f=0);k={videoId:d,currentTime:f};c&&(k.listId=c);g.n(e)&&(k.currentIndex=e);c&&(this.sa.o=c);this.sa.videoId=d;this.sa.index=e||0}else{var d=b.videoIds[b.index],f=b.currentTime||0;5>=f&&(f=0);var k={videoIds:d,videoId:d,currentTime:f};this.sa.g=[d];this.sa.index=0}this.sa.state=3;g.xG(this.sa,f);this.dc("Connecting with setPlaylist and params: "+g.Nd(k));this.b.connect({method:"setPlaylist",params:g.Nd(k)},
a,gF())}else this.dc("Connecting without params"),this.b.connect({},a,gF());lka(this)};g.h.dispose=function(){this.ha()||(this.publish("beforeDispose"),fI(this,3));g.eI.J.dispose.call(this)};g.h.O=function(){gI(this);iI(this);hI(this);g.Bd(this.D);this.D=window.NaN;g.Bd(this.F);this.F=window.NaN;this.o=null;g.uh(this.M);this.M.length=0;this.b.dispose();g.eI.J.O.call(this);this.g=this.sa=this.b=null};g.h.dc=function(a){g.DF("conn",a)};g.h.uJ=function(){this.A(2)};
g.h.hN=function(){this.dc("Channel opened");this.L&&(this.L=!1,hI(this),this.G=(0,g.Ad)((0,g.x)(function(){this.dc("Timing out waiting for a screen.");this.A(1)},this),15E3));Lja(ika(this.b),this.P)};g.h.dN=function(){this.dc("Channel closed");(0,window.isNaN)(this.B)?g.eF(!0):g.eF();this.dispose()};
g.h.eN=function(a){g.eF();(0,window.isNaN)(this.C())?(this.dc("Channel error: "+a+" without reconnection"),this.dispose()):(this.L=!0,this.dc("Channel error: "+a+" with reconnection in "+this.C()+" ms"),fI(this,2))};
g.h.fN=function(a){a.ya?this.dc("Received: action="+a.action+", params="+g.Nd(a.ya)):this.dc("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Kd(a.ya.devices);this.g=(0,g.N)(a,function(a){return new mF(a)});a=!!g.io(this.g,function(a){return"LOUNGE_SCREEN"==a.type});nI(this,a);break;case "loungeScreenConnected":nI(this,!0);break;case "loungeScreenDisconnected":qF(this.g,function(a){return"LOUNGE_SCREEN"==a.type});nI(this,!1);break;case "remoteConnected":var b=new mF(g.Kd(a.ya.device));
g.io(this.g,function(a){return a.Wa(b)})||g.rF(this.g,b);break;case "remoteDisconnected":b=new mF(g.Kd(a.ya.device));qF(this.g,function(a){return a.Wa(b)});break;case "gracefulDisconnect":break;case "playlistModified":oI(this,a);break;case "nowPlaying":nka(this,a);break;case "onStateChange":pI(this,a);break;case "onVolumeChanged":oka(this,a);break;case "onSubtitlesTrackChanged":mka(this,a);break;default:this.dc("Unrecognized action: "+a.action)}};
g.h.gN=function(a){a.ya?this.dc("Received: action="+a.action+", params="+g.Nd(a.ya)):this.dc("Received: action="+a.action);pka(this,a);qka(this,a);if(lI(this)){var b=this.sa.clone(),c=!1,d,e,f,k,l,p;a.ya&&(d=a.ya.videoId||a.ya.video_id,e=a.ya.videoIds||a.ya.video_ids,f=a.ya.state,k=a.ya.currentTime||a.ya.current_time,l=a.ya.volume,p=a.ya.muted,g.n(a.ya.currentError)&&g.Kd(a.ya.currentError));if("onSubtitlesTrackChanged"==a.action)d==g.wG(this.sa)&&(delete a.ya.videoId,g.Mq(a.ya)?this.sa.A=null:this.sa.A=
a.ya,this.publish("remotePlayerChange"));else if(g.wG(this.sa)||"onStateChange"!=a.action)"playlistModified"!=a.action&&"nowPlayingPlaylist"!=a.action||e?(d||"nowPlaying"!=a.action&&"nowPlayingPlaylist"!=a.action?d||(d=g.wG(this.sa)):g.zG(this.sa,""),e&&(e=e.split(","),AG(this.sa,e,d))):AG(this.sa,[]),g.BG(this.sa,d)&&jI(this,"getPlaylist"),d&&g.zG(this.sa,d),b.index==this.sa.index&&g.$E(b.g,this.sa.g)?"playlistModified"!=a.action&&"nowPlayingPlaylist"!=a.action||this.publish("remoteQueueChange"):
this.publish("remoteQueueChange"),g.n(f)&&(a=(0,window.parseInt)(f,10),a=(0,window.isNaN)(a)?-1:a,-1==a&&-1E3==this.sa.b&&(a=-1E3),0==a&&"0"==k&&(a=-1),c=c||a!=this.sa.b,this.sa.b=a,1==this.sa.b?kI(this):iI(this)),k&&(a=(0,window.parseInt)(k,10),g.xG(this.sa,(0,window.isNaN)(a)?0:a),c=!0),g.n(l)&&(a=(0,window.parseInt)(l,10),(0,window.isNaN)(a)||(c=c||this.sa.volume!=a,this.sa.volume=a),g.n(p)&&(p="true"==p,c=c||this.sa.muted!=p,this.sa.muted=p)),c&&this.publish("remotePlayerChange")}};
g.h.DQ=function(){if(this.o){var a=this.o;this.o=null;this.sa.videoId!=a&&jI(this,"getNowPlaying")}};g.eI.prototype.subscribe=g.eI.prototype.subscribe;g.eI.prototype.unsubscribeByKey=g.eI.prototype.xd;g.eI.prototype.S=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.C())?lI(this)&&(a=1):a=2);return a};g.eI.prototype.getProxyState=g.eI.prototype.S;g.eI.prototype.A=function(a){this.dc("Disconnecting with "+a);gI(this);this.publish("beforeDisconnect",a);1==a&&g.eF();this.b.disconnect(a);this.dispose()};
g.eI.prototype.disconnect=g.eI.prototype.A;g.eI.prototype.R=function(){var a=this.sa;if(this.o){var b=a=this.sa.clone(),c=this.o,d=a.index,e=b.videoId;b.videoId=c;b.index=d;c!=e&&uG(b)}return g.CG(a)};g.eI.prototype.getPlayerContextData=g.eI.prototype.R;
g.eI.prototype.W=function(a){var b=new g.sG(a);b.videoId&&b.videoId!=this.sa.videoId&&(this.o=b.videoId,g.Bd(this.D),this.D=(0,g.Ad)((0,g.x)(this.DQ,this),5E3));var c=[];this.sa.o==b.o&&this.sa.videoId==b.videoId&&this.sa.index==b.index&&g.$E(this.sa.g,b.g)||c.push("remoteQueueChange");this.sa.b==b.b&&this.sa.volume==b.volume&&this.sa.muted==b.muted&&g.yG(this.sa)==g.yG(b)&&g.Nd(this.sa.A)==g.Nd(b.A)||c.push("remotePlayerChange");this.sa.reset(a);(0,g.D)(c,function(a){this.publish(a)},this)};
g.eI.prototype.setPlayerContextData=g.eI.prototype.W;g.eI.prototype.N=function(){return this.b.A.loungeIdToken};g.eI.prototype.getLoungeToken=g.eI.prototype.N;g.eI.prototype.H=function(){var a=this.b.getDeviceId(),b=g.io(this.g,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});return b?b.id:""};g.eI.prototype.getOtherConnectedRemoteId=g.eI.prototype.H;g.eI.prototype.C=function(){var a=this.b;return a.g.enabled?a.g.B-(0,g.G)():window.NaN};g.eI.prototype.getReconnectTimeout=g.eI.prototype.C;
g.eI.prototype.Y=function(){if(!(0,window.isNaN)(this.C())){var a=this.b.g;a.enabled&&(a.stop(),a.start(),a.C())}};g.eI.prototype.reconnect=g.eI.prototype.Y;g.eI.prototype.X=function(a,b){jI(this,a,b);mI(this)};g.eI.prototype.sendMessage=g.eI.prototype.X;g.VF.prototype.$_st=g.VF.prototype.start;g.VF.prototype.$_gspc=g.VF.prototype.xS;g.VF.prototype.$_gsppc=g.VF.prototype.mD;g.VF.prototype.$_c=g.VF.prototype.contains;g.VF.prototype.$_g=g.VF.prototype.get;g.VF.prototype.$_a=g.VF.prototype.pm;g.VF.prototype.$_un=g.VF.prototype.em;g.VF.prototype.$_r=g.VF.prototype.remove;g.VF.prototype.$_gs=g.VF.prototype.zd;g.VF.prototype.$_gos=g.VF.prototype.lD;g.VF.prototype.$_s=g.VF.prototype.subscribe;g.VF.prototype.$_ubk=g.VF.prototype.xd;g.qI.prototype.listen=function(a,b,c,d){c=(0,g.x)(c,d||this.g);a=g.sh(a,b,c);this.b.push(a);return a};g.qI.prototype.Ia=function(a){g.uh(a);g.Ga(this.b,a)};g.qI.prototype.removeAll=function(){g.uh(this.b);this.b.length=0};})(_yt_m);
